version: '3.3'
services:

  ci-db:
    container_name: ci-db
    image: mysql:8.0

    environment:
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=eyacherni
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  ci-app:
    build:
      context: .
    container_name: ci-spring
    image: tpachat/ci:latest
    ports:
      - "8089:8089"
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_USERNAME=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=eyacherni
      - MYSQL_PORT=3306
      



volumes:
  dbvol:
